### ISSUE TITLE
Several little problems that needs to be corrected

### ISSUE THREAD

**Issue by dyvim** [Trestolt/dsa5-tsa-edition#3]
Hi @Trestolt 

Thanks for this sheet that is very promising.
For your information it is already translated in french. (I've done the translation)

I wanted to inform you about several little problems I have noticed.

- line 6167 :  a data-i18n tag is missing for patzer

- lines 430 to 471 : all data-i18n tags are missing

- lines 4716 and 4913 : You are using radio buttons named "Alle" but they don't have the value "checked". So sometimes you add a spell and you can't see it :)

- lines 5985, 5986, 6207, 6736 : the value "Waffenlos" is not translatable. It should be between the `<td>` and `</td>` tags with a data-i18n tag to the td (for example, it is not the only solution)

- in the combat tab and equipment tab there are a lot of columns that need an auto-width parameter. The columns at right displays actually out of the tab (for me)
Note that for all titles that needs to be translated an auto-width parameter is generally usefull.

Best Regards (ang again thanks for your sheet)

**Comment by dyvim** [comment]
Hallo @Trestolt

Vielen Dank für dieses Charakterbogen , das sehr vielversprechend ist.
Zu Ihrer Information ist es bereits auf Französisch übersetzt. (Ich habe die Übersetzung gemacht)

Ich wollte dich über einige kleine Probleme informieren, die mir aufgefallen sind.

Zeile 6167 : ein data-i18n-Tag fehlt für patzer

Zeilen 430 bis 471 : alle data-i18n-Tags fehlen

Zeilen 4716 und 4913: Du verwendest Auswahlknöpfe namens "Alle", die aber nicht den Wert "checked" haben. Manchmal fügt man also einen Zauber hinzu und kann ihn nicht sehen :)

Zeilen 5985, 5986, 6207, 6736 : der Wert "Waffenlos" ist nicht übersetzbar. Es sollte zwischen den Tags `<td>` und `</td>` mit einem data-i18n-Tag zum td liegen (z.B. ist es nicht die einzige Lösung).

in der Registerkarte Kampf und der Registerkarte Ausrüstung gibt es viele Spalten, die einen Parameter für die automatische Breite benötigen. Die Spalten rechts zeigen tatsächlich aus der Registerkarte (für mich) an.
Beachten Sie, dass für alle zu übersetzenden Titel ein Parameter für die automatische Breite im Allgemeinen sinnvoll ist.

Mit freundlichen Grüßen (und nochmals vielen Dank für dein Charakterbogen )

**Comment by Trestolt** [comment]
Hi @dyvim ,

sorry, that I haven't checked the issues earlier. 
Thanks for your feedback and the translations.
Actually I am working on the missing data-i18n-Tags, they will be published soon.

I'm also working on the design elements, but it will take some more time.

'Waffenlos' can be overwritten in the equipment tab. I haven't figured out yet, how to set translation tags for values.

Regards

**Comment by dyvim** [comment]
Hello @Trestolt 

You're welcome. Thanks for your work.

Concerning the translations for values you can use this method that has been given to me by Anduh

> If you want to change values of an input, they need to be replaced by sheetworkers, the ars magica sheet shows at row 1584 & row 1768 how this is made. Considering you want to change values of existing stats/inputs, you don't create new hidden inputs as I did, just use the right names in the sheetworkers when you replace their values. i18n - roll queries explains what is happening.

> For example, to change the value of `<div class="sheet-row"><input type="text" name="attr_agilityname1" class="sheet-main-skill" value="Agility" readonly></div>`, you would need to add this to the botton of the html:

```
<script type="text/worker">
 on("sheet:opened", function(eventInfo){
     setAttrs({
         agilityname1:  getTranslationByKey("agility") 
     });
 });
 </script>
```

> and see that there exist a corresponding row on the translation.json following the pattern it have there:

`"agility": "Agilty",`

> When you add more, the sheetworker will start to look like:

```<script type="text/worker">
on("sheet:opened", function(eventInfo){
    setAttrs({
        agilityname1:  getTranslationByKey("agility"),
        agilityname2:  getTranslationByKey("agility"),
        strengthname1:  getTranslationByKey("strength") 
    });
});
</script>```

**Comment by Trestolt** [comment]
Hi,  I have worked on the design. I have left more space for translations. If there are still some issues please let me know.

I have found a very simple solution for the 'Waffenlos' issue. I have replaced the value with a placeholder:

       data-i18n-placeholder="waffenlos" placeholder="Waffen"

I haven't found a solution for options group labels yet.

**Comment by dyvim** [comment]
Hello Trestolt.
I've seen your pull request this afternoon. i'll check that tomorrow after the commit.
It looks interesting (even for someone that is not an expert on CSS)
Your last week modifications were realy cool already.
I'll probably try a one-shot soon with your sheet. I'll let you know if I have returns from the players and if I have also.

By the way, I have a suggestion. The previous DSA5 sheet that inspired you a lot had sub-tabs for the skills tab. Can you do the same thing (one sub tab for physical skills, one for social and so on)? For the moment the fact that you have to scroll through the tab is not very practicall. (at my sense but you can disagree, it's only my point of view)

BRgds and keep up the good work :)

**Comment by dyvim** [comment]
Rahh... It seems that I'll have to wait a week to see your latest modifications

**Comment by Trestolt** [comment]
The update should be now available on the roll20 server. 
I have discussed the skill tab with other people at RatCon if i do subtabs or not. The advantage of this design is, that you can search for a skill with ctrl-f. Many people don't know where to look for a skill e. g. is Dancing a social or physical skill? Is Trading a social or crafting skill?

Another idea is to use jump marker to scroll faster, but that has a lower priority compared to the npc sheet.

**Comment by Trestolt** [comment]
but you are right, the solution with placeholder are planned for the next update.

**Comment by dyvim** [comment]
"jump markers" is a good idea :)

**Comment by dyvim** [comment]
what will you change for the NPC sheet?

**Comment by Trestolt** [comment]
The idea is to enter values that are calculated for a pc. e. g. combat values or common attributes. In adventures or other books you have a box with only a few stats for an npc.

**Comment by dyvim** [comment]
You mean to be able to copy-paste a NPC blockstat in the actual sheet? (i've heard of a french sheet that allows that it's "chroniques oubliées fantasy")
or just a simplified version of the sheet with only the fields corresponding to a NPC/monster blockstat?

**Comment by Trestolt** [comment]
I mean a simplified version of the sheet.

**Comment by dyvim** [comment]
That would be great. I've just tried to create a bear as a NPC and it wasn't easy with the actual sheet.

**Comment by Trestolt** [comment]
I think the most issues are solved.  Please contact me in Discord if not.

**Comment by dyvim** [comment]
cool. i'll check ASAP
